[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  targetPort = 5173

# Cache built assets & images aggressively (not HTML)
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
  Cache-Control = "no-cache"
